### PR TITLE
stream indexed msgs instead of all at once

### PR DESCRIPTION
**Pull request by staltz**
This initially seems like just a refactor, but in reality it's a performance improvement.

When using `toCallback`, it will get *all* indexable msgs. Using `toPullStream` we will get ~50 each time. We *should* expect the indexable msgs to be a huge collection (e.g. `votes`) because when working on partial replication we should assume that the full replication is huge.

Also, because `resolveIndexFeed` is used over the network, when a remote peer calls `resolveIndexFeed`, they could get only a few, and then decide to abort the stream. Using `toCallback` under the hood would mean that the remote peer would have to wait for us to fetch everything, and when the remote peer receives it, it would receive all at once as a fire hose.

### CODE REVIEW

**Comment by staltz** [comment]
Oooh, I also realize now there is the other `toCallback` above it that populates the `Map`. I wonder if there is a way of streaming both of these...

(putting this in draft mode)

**Comment by arj03** [comment]
Is this still draft or ready for review?

**Comment by staltz** [comment]
Still draft, I didn't give high priority to fixing this yet.

**Comment by arj03** [comment]
Lets park this one for now, we might not even need this RPC

**Pull request closed without merging**
